version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: simplecov-console
    versions:
    - 0.9.0
  - dependency-name: ffi
    versions:
    - 1.14.2
